apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mency-node-static
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mency-node-static
    spec:
      volumes:
        - name: static-volume
          hostPath:
            path: /opt/efs/config/simple-node/static
        - name: config-volume
          #hostPath:
            #path: /Users/mency/Git/Kubernetes/containers/node-app/webapp/config
          #  this assumes e.g. kubectl create configmap sample-node --from-file=./webapp/config/default.json  has been run earlier
          configMap:
            name: sample-node
            items:
            - key: dev.json
              path: dev.json
      containers:
        - name: simple-node
          image: mencywoo/simple-node:latest
          imagePullPolicy: Always
          env:
            -
              name:  NODE_ENV
              value: dev
          ports:
            -
              containerPort: 8080
          volumeMounts:
          - mountPath: /opt/webapp/config
            name: config-volume
          - mountPath: /opt/webapp/static
            name: static-volume
