apiVersion: v1
kind: Pod
metadata:
  name: mency-mysql-flask
spec:
  containers:
  - name: mency-mysql-flask
    image: mencywoo/mysql-flask
    imagePullPolicy: IfNotPresent
    env:
      -
          name:  CONFIG
          value: /etc/config/mysql-docker.cfg
    ports:
      -
        containerPort: 5000
    volumeMounts:
    - mountPath: /etc/config
      name: config-volume
  volumes:
  - name: config-volume
    hostPath:
      # directory location on host
      path: /Users/mency/Git/Kubernetes/containers/flask-config-dir
