apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mency-flask
    spec:
      volumes:
        - name: config-volume
          hostPath:
            # directory location on host
            path: /Users/mency/Git/Non-client/mysql/config-volume
      containers:
        - name: mency-mysql-flask
          image: mencywoo/mysql-flask
          imagePullPolicy: IfNotPresent
          env:
            -
              name:  CONFIG
              value: /etc/config/mysql_docker.cfg
          ports:
            -
              containerPort: 5000
          volumeMounts:
          - mountPath: /etc/config
            name: config-volume
